[package]
name = "derive"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "2"
quote = "1"
proc-macro2 = "1"
proc-macro-error2 = "2"
darling = { version = "0.20", features = ["suggestions"] }

[lib]
proc-macro = true